import Link from "next/link";
import { pageMetadata, siteUrl } from "@/lib/seo";
import { projects } from "@/data/projects";
export const metadata = pageMetadata("fa", "/", "مهرداد افشاری | توسعه‌دهنده نرم‌افزار و هوش مصنوعی", "وب‌سایت رسمی مهرداد افشاری، توسعه‌دهنده نرم‌افزار و پایگاه داده با بیش از ۱۳ سال تجربه و دانشجوی کارشناسی ارشد علوم کامپیوتر دانشگاه روستوک آلمان. پروژه‌های هوش مصنوعی، RAG و عامل‌های هوشمند.");
const selected = projects.filter(p => ["ai-operations-agent","ai-meeting-assistant","ai-job-application-assistant","ai-knowledge-assistant"].includes(p.id));
const descriptions: Record<string,string> = {
 "ai-operations-agent":"سامانه عامل هوشمند با LangGraph و FastAPI، کنترل سیاست‌ها، تأیید انسانی و زیرساخت ابری تعریف‌شده با Terraform.",
 "ai-meeting-assistant":"پیاده‌سازی محلی تبدیل گفتار به متن، خلاصه‌سازی جلسات و پرسش‌وپاسخ بر اساس متن جلسه.",
 "ai-job-application-assistant":"تحلیل تطابق رزومه و آگهی شغلی با امتیازدهی شفاف و تولید متن با محدودیت‌های مبتنی بر شواهد.",
 "ai-knowledge-assistant":"دستیار اسناد مبتنی بر RAG با مدل‌های محلی، جستجوی برداری و نمایش منابع پاسخ."};
export default function PersianPage(){return <>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"ProfilePage","@id":siteUrl+"/fa#profile","url":siteUrl+"/fa","name":"مهرداد افشاری | توسعه‌دهنده نرم‌افزار و هوش مصنوعی","inLanguage":"fa","mainEntity":{"@id":siteUrl+"/#person"}})}} />
<header className="border-b border-white/10 bg-[#080b12] text-white"><nav aria-label="ناوبری اصلی" className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-6 py-5"><a href="/fa" className="font-bold">مهرداد افشاری</a><div className="flex gap-4 text-sm"><a href="/" lang="en">English</a><a href="/de" lang="de">Deutsch</a></div></nav></header>
<main id="main-content" className="min-h-screen bg-[#080b12] text-white"><div className="mx-auto max-w-6xl space-y-20 px-6 py-20">
<section className="max-w-4xl"><p className="text-blue-300">Mehrdad Afshari · Rostock, Germany</p><h1 className="mt-5 text-4xl font-bold leading-relaxed sm:text-6xl">مهرداد افشاری</h1><h2 className="mt-3 text-2xl text-blue-200">توسعه‌دهنده نرم‌افزار، پایگاه داده و هوش مصنوعی</h2><p className="mt-7 text-lg leading-9 text-slate-300">بیش از ۱۳ سال تجربه حرفه‌ای در توسعه نرم‌افزار، طراحی پایگاه داده و خودکارسازی فرایندهای سازمانی دارم. اکنون دانشجوی کارشناسی ارشد علوم کامپیوتر در دانشگاه روستوک آلمان هستم و در کنار سابقه توسعه نرم‌افزار، روی ساخت کاربردهای عملی هوش مصنوعی، عامل‌های هوشمند و سیستم‌های مبتنی بر مدل‌های زبانی کار می‌کنم.</p><div className="mt-8 flex flex-wrap gap-3"><a className="rounded-full bg-blue-600 px-6 py-3" href="#projects">مشاهده پروژه‌ها</a><a className="rounded-full border border-white/25 px-6 py-3" href="/cv/mehrdad-afshari-cv.pdf">رزومه انگلیسی (PDF)</a></div></section>
<section id="about" className="max-w-4xl"><h2 className="text-3xl font-bold">درباره من</h2><p className="mt-5 leading-9 text-slate-300">تجربه حرفه‌ای من شامل توسعه برنامه‌های سازمانی با C# و .NET، کار با SQL Server، گزارش‌گیری و طراحی راهکارهای نرم‌افزاری است. در پروژه‌های جدید، این تجربه را با Python، FastAPI، Next.js، LangGraph، RAG و مدل‌های زبانی محلی ترکیب کرده‌ام. تمرکز من ساخت نرم‌افزارهای قابل نگهداری، قابل بررسی و کاربردی است.</p></section>
<section id="projects"><h2 className="text-3xl font-bold">پروژه‌های منتخب</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{selected.map(p=><article key={p.id} className="rounded-2xl border border-white/15 bg-white/5 p-6"><h3 className="text-xl font-semibold" dir="ltr">{p.title}</h3><p className="mt-4 leading-8 text-slate-300">{descriptions[p.id]}</p><div className="mt-5 flex flex-wrap gap-5 text-sm"><Link className="text-blue-300" href={`/projects/${p.id}`}>مطالعه جزئیات به انگلیسی ←</Link>{p.github&&<a className="text-blue-300" href={p.github} target="_blank" rel="noopener noreferrer">GitHub</a>}</div></article>)}</div></section>
<section><h2 className="text-3xl font-bold">تحصیلات و تجربه</h2><div className="mt-6 space-y-5 leading-8 text-slate-300"><p><strong className="text-white">تحصیلات:</strong> کارشناسی ارشد علوم کامپیوتر، دانشگاه روستوک آلمان (در حال تحصیل)</p><p><strong className="text-white">تجربه:</strong> توسعه‌دهنده ارشد نرم‌افزار و پایگاه داده در Namaad Iran Co. (۲۰۱۶ تا ۲۰۲۴)؛ فعالیت مستقل در توسعه وب از سال ۲۰۱۱</p><p><strong className="text-white">زمینه‌های فنی:</strong> Python، FastAPI، LangGraph، RAG، Next.js، TypeScript، C#، .NET و SQL Server</p></div></section>
<section id="contact"><h2 className="text-3xl font-bold">ارتباط با من</h2><p className="mt-4 text-slate-300">برای همکاری حرفه‌ای یا آشنایی بیشتر با پروژه‌ها:</p><div className="mt-6 flex flex-wrap gap-5 text-blue-300"><a href="mailto:afshari@outlook.com">ایمیل</a><a href="https://github.com/Mehrdad-Afshari" target="_blank" rel="noopener noreferrer">GitHub</a><a href="https://linkedin.com/in/mehrdadafshari" target="_blank" rel="noopener noreferrer">LinkedIn</a></div></section>
</div></main><footer className="bg-[#080b12] px-6 py-8 text-center text-sm text-slate-400">© Mehrdad Afshari · <a href="/">English</a> · <a href="/de">Deutsch</a></footer></>}
